version: '0.0.1'

services:
  movie_quote_api:
    container_name: movie_quote_api
    build:
      context: ./
    ports:
      - "8081:8000"
    volumes:
      - ./:/var/www/
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
